[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
